# Generated by Django 4.2.10 on 2024-02-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='word',
            new_name='name',
        ),
    ]
