# Generated by Django 4.2.10 on 2024-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_rename_word_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='authors',
            field=models.ManyToManyField(to='searcher.author'),
        ),
    ]
