# Generated by Django 4.2.10 on 2024-02-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_remove_thesis_authors_remove_thesis_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors', to='searcher.thesis'),
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='panelist', to='searcher.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='searcher.thesis')),
            ],
        ),
    ]
