# Generated by Django 4.2.10 on 2024-02-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0006_alter_panelist_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelist',
            name='thesis',
        ),
        migrations.RemoveField(
            model_name='author',
            name='thesis',
        ),
        migrations.AddField(
            model_name='thesis',
            name='authors',
            field=models.ManyToManyField(to='searcher.author'),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Panelist',
        ),
    ]
