# Generated by Django 4.2.10 on 2024-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0007_remove_panelist_thesis_remove_author_thesis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='keywords',
            field=models.ManyToManyField(to='searcher.keyword'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='panelists',
            field=models.ManyToManyField(to='searcher.panelist'),
        ),
    ]
