# Generated by Django 4.2.10 on 2024-02-18 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0013_adviser_thesis_adviser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='published_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thesis',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['-published_date'], name='searcher_th_publish_2e7ef9_idx'),
        ),
    ]
