# Generated by Django 4.2.10 on 2024-02-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0014_alter_thesis_options_thesis_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='searcher.thesis')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='searcher_co_created_82a9e1_idx')],
            },
        ),
    ]
